### ISSUE TITLE
Using System.Random causes issues on Mac Silicon Unity

### ISSUE THREAD

**Issue by jdell64** [needle-mirror/com.unity.burst#1]
Honestly, I'm not sure this is the right repo to post on, but when compiling a game on my Mac using Apple Silicon, I get:

`System.TypeInitializationException: The type initializer for 'System.Random' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Sys' threw an exception. ---> System.DllNotFoundException: /Applications/Unity/Hub/Editor/2022.1.0b7/Unity.app/Contents/MonoBleedingEdge/lib/../lib/libmono-native.dylib assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Interop+Sys.LChflagsCanSetHiddenFlag()
  at Interop+Sys..cctor () [0x00000] in <3cc0041a7bf849d5a824197f18576c2b>:0 `

I've removed all instances in my code and other assets (replacing them with UnityEngine.Random), but Burst still has a few System.Random s:

`  public object Value
            {
                get
                {
                    int length = SphereCulling.BenchCount;
                    var job = new SphereCullingFloat4AOSJob()
                    {
                        Spheres = new NativeArray<float4>(length, Allocator.Persistent),
                        Against = new float4(0, 0, 0, 1)
                    };

                    var random = new System.Random(0);
                    for (int i = 0; i < job.Spheres.Length; i++)
                    {
                        // Most don't intersects
                        var x = random.Next(100) + 3.0f;
                        if (i == job.Spheres.Length / 2)
                        {
                            // only this one
                            x = 0.5f;
                        }
                        job.Spheres[i] = new float4(x, x, x, 1.0f);
                    }

                    return job;
                }
            }`

etc...

Can I change these in my code base / Will this negatively effect the compile for the iOS target?

**Comment by marwie** [comment]
Hello, 

sorry this is not the right repo unfortunately - we are only mirroring unity packages and not officially related. Please report issues with packages as a bug to Unity directly.
